// Coordonnees de contact : voir src/config/contact.js (source unique).
import { CONTACT } from '../../config/contact.js';
const dict = {
  fr: {
    title: 'Demander une démonstration',
    intro: 'Vous souhaitez découvrir Farm Control System ? Demandez une démonstration personnalisée.',

    fullName: 'Nom complet',
    company: 'Entreprise / exploitation',
    email: 'Adresse email',
    phone: 'Téléphone',
    role: 'Fonction',
    needType: 'Type de besoin',
    preferredContact: 'Moyen de contact préféré',
    message: 'Message',
    consent: 'J’accepte que mes données soient traitées pour répondre à ma demande.',
    submit: 'Envoyer',
    sending: 'Envoi en cours...',
    newRequest: 'Envoyer une autre demande',
    errRequired: 'Ce champ est obligatoire.',
    errEmail: 'Veuillez saisir une adresse email valide.',
    errPhone: 'Veuillez saisir un numéro de téléphone valide.',
    errMessageShort: 'Merci de détailler un peu votre demande (10 caractères minimum).',
    errConsent: 'Vous devez accepter le traitement de vos données pour continuer.',
    errorText: "L'envoi a échoué. Réessayez dans un instant ou écrivez-nous directement par email.",
    errorNotConfigured: "Le formulaire n'est pas encore configuré. Écrivez-nous directement par email en attendant.",
    successTitle: 'Merci !',
    successText: 'Votre demande a bien été envoyée. Notre équipe vous répondra rapidement.',

    needOptions: ['Démonstration', 'Devis', 'Support technique', 'Autre'],
    contactOptions: ['Email', 'Téléphone', 'WhatsApp'],

    sidebarTitle: 'Nous contacter',
    contactEmail: CONTACT.email,
    contactPhone: CONTACT.phoneDisplay,
    brandTagline: 'La gestion intelligente de votre exploitation', // deja valide (page Accueil)
  },
  en: {
    title: 'Request a demo',
    intro: 'Want to discover Farm Control System? Request a personalized demo.',
    fullName: 'Full name',
    company: 'Company / farm',
    email: 'Email address',
    phone: 'Phone',
    role: 'Role',
    needType: 'Type of request',
    preferredContact: 'Preferred contact method',
    message: 'Message',
    consent: 'I agree that my data will be processed to respond to my request.',
    submit: 'Send',
    sending: 'Sending...',
    newRequest: 'Send another request',
    errRequired: 'This field is required.',
    errEmail: 'Please enter a valid email address.',
    errPhone: 'Please enter a valid phone number.',
    errMessageShort: 'Please give us a few more details (10 characters minimum).',
    errConsent: 'You must accept the processing of your data to continue.',
    errorText: 'Sending failed. Please try again shortly, or email us directly.',
    errorNotConfigured: 'The form is not configured yet. Please email us directly in the meantime.',
    successTitle: 'Thank you!',
    successText: 'Your request has been sent. Our team will get back to you shortly.',
    needOptions: ['Demo', 'Quote', 'Technical support', 'Other'],
    contactOptions: ['Email', 'Phone', 'WhatsApp'],
    sidebarTitle: 'Contact us',
    contactEmail: CONTACT.email,
    contactPhone: CONTACT.phoneDisplay,
    brandTagline: 'Smart management for your farm',
  },
  ar: {
    title: 'اطلب عرضاً تجريبياً',
    intro: 'تريد اكتشاف Farm Control System؟ اطلب عرضاً تجريبياً مخصصاً.',
    fullName: 'الاسم الكامل',
    company: 'المؤسسة / الاستغلالية',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    role: 'الوظيفة',
    needType: 'نوع الطلب',
    preferredContact: 'وسيلة التواصل المفضلة',
    message: 'الرسالة',
    consent: 'أوافق على معالجة بياناتي للرد على طلبي.',
    submit: 'إرسال',
    sending: 'جاري الإرسال...',
    newRequest: 'إرسال طلب آخر',
    errRequired: 'هذا الحقل إلزامي.',
    errEmail: 'يرجى إدخال بريد إلكتروني صالح.',
    errPhone: 'يرجى إدخال رقم هاتف صالح.',
    errMessageShort: 'يرجى تقديم المزيد من التفاصيل (10 أحرف على الأقل).',
    errConsent: 'يجب الموافقة على معالجة بياناتك للمتابعة.',
    errorText: 'فشل الإرسال. يرجى المحاولة بعد قليل أو مراسلتنا مباشرة عبر البريد الإلكتروني.',
    errorNotConfigured: 'لم تتم تهيئة الاستمارة بعد. يرجى مراسلتنا مباشرة عبر البريد الإلكتروني في انتظار ذلك.',
    successTitle: 'شكراً لكم!',
    successText: 'تم إرسال طلبكم بنجاح. سيتواصل معكم فريقنا قريباً.',
    needOptions: ['عرض تجريبي', 'عرض سعر', 'دعم تقني', 'أخرى'],
    contactOptions: ['البريد الإلكتروني', 'الهاتف', 'واتساب'],
    sidebarTitle: 'اتصل بنا',
    contactEmail: CONTACT.email,
    contactPhone: CONTACT.phoneDisplay,
    brandTagline: 'الإدارة الذكية لاستغلاليتكم الفلاحية',
  },
};

export default dict;
